name: Say hello

on:
  push:
    branches:
      - main

jobs:
  say_hello:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello world
        run: echo "Hello, Guille!"
      - name: dime la fecha
        run: date
      - run: ls -l